### Site Settings ###
title: Ricardo Villanueva
description: >-
  I help companies of any size solve problems 
  by developing tailored solutions 
  using the latest technology 
  and partnering with the best businesses to achieve success.
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: ricard0javier/com-ricardovz-web # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme: YoussefRaafatNasry/portfolYOU
open_new_tab: true # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/** # For Documentation Only

### Author Info ###
author:
  name: Ricardo Villanueva
  image: assets/img/profile_pic.jpg
  # behance           : your_username
  # dribbble          : your_username
  email: me@ricardovz.com
  # facebook          : your_username
  github: ricard0javier
  # gitlab            : your_username
  # instagram         : ricardo.uk
  # kaggle            : your_username
  linkedin: villanuevaricardo
  # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements: # For Documentation Only
    output: true # For Documentation Only

### Disqus ###
disqus:
  shortname: RicardoVZ # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: true # Set true to enable analytics
  google:
    tracking_id: G-RD3ZV7N813

### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: true
  username: villanueva.ricardo
  color: "#007bff"
  message: "Thank you for visiting." # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope: # For Documentation Only
      path: "" # For Documentation Only
      type: "elements" # For Documentation Only
    values: # For Documentation Only
      layout: "element" # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
